<?php
    require_once __DIR__ . '/../vendor/autoload.php';

    use App\DatabaseConnection;

    $connection = DatabaseConnection::get();

    $connection->query(
        "CREATE TABLE IF NOT EXISTS classes 
                (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    category text,
                    name text
                );
        ",
        []
    );

    $connection->query(
        "CREATE TABLE IF NOT EXISTS questions 
                (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    option_a INTEGER,
                    option_b INTEGER,
                    CONSTRAINT fk_option_a
                        FOREIGN KEY(option_a)
                            REFERENCES classes(id),
                    
                    CONSTRAINT fk_option_b
                        FOREIGN KEY(option_b)
                            REFERENCES classes(id)
                );
        ",
        []
    );

    $connection->query(
        "CREATE TABLE IF NOT EXISTS answers 
                (
                    owner_id varchar(16),
                    question INTEGER,
                    answer text,
                    CONSTRAINT fk_question
                        FOREIGN KEY(question)
                            REFERENCES questions(id)
                );
        ",
        []
    );

    $connection->query(
        "CREATE INDEX IF NOT EXISTS owner_index ON answers(owner_id)",
        []
    );
?>